apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: arm-exporter
  namespace: monitoring
  labels:
    k8s-app: arm-exporter
spec:
  template:
    metadata:
      name: arm-exporter
      labels:
        k8s-app: arm-exporter
    spec:
      hostNetwork: true
      containers:
      - image: carlosedp/arm_exporter
        name: arm-exporter
        ports:
        - name: http
          containerPort: 9243
          hostPort: 9243
