apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
spec:
  rules:
  - host: prometheus.internal.voeni.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-k8s
          servicePort: web
