apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: smtp-server
  name: smtp-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: smtp-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: smtp-server
    spec:
      containers:
      - image: carlosedp/docker-smtp
        imagePullPolicy: Always
        name: smtp-server
        ports:
        - containerPort: 25
          protocol: TCP
        env:
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: smtp-account
              key: username
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-account
              key: password
        - name: DISABLE_IPV6
          value: "True"
        - name: RELAY_DOMAINS
          value: ":192.168.0.0/24:10.0.0.0/16"
        resources: {}
      restartPolicy: Always
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: smtp-server
  name: smtp-server
  namespace: monitoring
spec:
  ports:
  - nodePort: 30025
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    run: smtp-server
  type: NodePort
