apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.internal.voeni.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-main
          servicePort: web

