apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - image: carlosedp/snmp_exporter:v0.9.0
        name: snmp-exporter
        ports:
        - containerPort: 9116
          name: metrics
